apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: lws-sample
  annotations:
    leaderworkerset.sigs.k8s.io/exclusive-topology: rack
spec:
  replicas: 2
  leaderWorkerTemplate:
    size: 4
    leaderTemplate:
      spec:
        containers:
        - name: leader
          image: busybox
          command: ["sh"]
          args: ["-c", "echo start && sleep infinity"]
    workerTemplate:
      spec:
        containers:
        - name: worker
          image: busybox
          command: ["sh"]
          args: ["-c", "echo start && sleep infinity"]
  rolloutStrategy:
    type: RollingUpdate
    rollingUpdateConfiguration:
      maxUnavailable: 1
      maxSurge: 1
