apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jobset-sample
spec:
  replicatedJobs:
    - name: leaders
      replicas: 1
      template:
        spec:
          template:
            spec:
              containers:
              - name: leader
                image: busybox
                command: ["/bin/sh"]
                args: ["-c", "echo 'start'; sleep 10; echo 'end'"]
    - name: workers
      replicas: 2
      template:
        spec:
          template:
            spec:
              containers:
              - name: worker
                image: busybox
                command: ["/bin/sh"]
                args: ["-c", "echo 'start'; sleep 10; echo 'end'"]
      dependsOn:
      - name: leaders
        status: Complete
