apiVersion: jobset.x-k8s.io/v1alpha2
kind: JobSet
metadata:
  name: jobset-sample
  annotations:
    alpha.jobset.sigs.k8s.io/exclusive-topology: rack
spec:
  replicatedJobs:
    - name: workers
      replicas: 2
      template:
        spec:
          backoffLimit: 0
          template:
            spec:
              containers:
              - name: worker
                image: busybox
                command: ["/bin/sh"]
                args:
                  - "-c"
                  - |
                    echo 'start'
                    sleep 10
                    echo 'end'
